# แบบฝึกหัด 8

---

In [2]:
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats.proportion import proportions_ztest

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

8.1 ร้านค้าออนไลน์ขายเมล็ดพืชหายากชนิดหนึ่ง อ้างว่าเมล็ดที่ขายมีเปอร์เซ็นต์การงอกสูงกว่า 90% จากการทดลองของลูกค้ารายหนึ่งได้สั่งซื้อเมล็ดมาทั้งหมด 100 เมล็ดและพบว่ามี 14 เมล็ดที่ไม่งอก จงทดสอบคำกล่าวอ้างของร้านค้าว่าเป็นจริงหรือไม่ที่ระดับนัยสำคัญ 0.05 หากถือว่าอัตราการงอกของเมล็ดพืชดังกล่าวมีการแจกแจงแบบปกติ

In [5]:
#แสดงสมมติฐาน พร้อมวิธีหาค่าcal ค่าp-value และการสรุปผล 
n = 100
p0 = 90 / 100 
p_hat = (100 - 14) / 100

z_cal = (p_hat - p0) / np.sqrt((p0 * (1 - p0)) / n)
z_cri = stats.norm.isf(0.05)

p_val = stats.norm.sf(z_cal)
print(p_val) # 0.9087887802741323
print("p-value > 0.05 ดังนั้น ยอมรับ H0 นั่นคือ เมล็ดที่ขายมีเปอร์เซ็นต์การงอก <= 90%")

0.9087887802741323
p-value > 0.05 ดังนั้น ยอมรับ H0 เมล็ดที่ขายมีเปอร์เซ็นต์การงอก <= 90%

8.2 สืบเนื่องจากข้อ 8.1 พบว่ามีร้านค้าออนไลน์อีกเจ้าซึ่งขายเมล็ดพืชหายากชนิดเดียวกันนี้ อ้างว่าเมล็ดที่ขายมีเปอร์เซนต์การงอกสูงกว่า 95% จึงสั่งซื้อมา 50 เมล็ดพบว่ามี 4 เมล็ดที่ไม่งอก จงทดสอบว่าร้านค้านี้ขายเมล็ดซึ่งมีเปอร์เซ็นต์การงอกสูงกว่าร้านค้าแรกมากกว่าหรือเท่ากับ 5% หรือไม่ ที่ระดับนัยสำคัญ 0.05

In [6]:
#แสดงสมมติฐาน พร้อมวิธีหาค่าcal ค่าp-value และการสรุปผล 
n1 = 100
n2 = 50

x1 = 100 - 14
x2 = 50 - 4

p0 = 5 / 100
p_hat = (x1 + x2) / (n1 + n2)
p_hat1 = x1 / n1
p_hat2 = x2 / n2

z_cal = ((p_hat1 - p_hat2) - p0) / np.sqrt(p_hat * (1 - p_hat) * (1 / n1 + 1 / n2))
z_cri - stats.norm.ppf(0.05)

p_val = stats.norm.cdf(z_cal)
print(p_val) # 0.02533051657624718
print("p-value < 0.05 ดังนั้น ยอมรับ H1 นั่นคือ ร้านค้านี้ขายเมล็ดซึ่งมีเปอร์เซ็นต์การงอกสูงกว่าร้านค้าแรก < 5%")

0.02533051657624718
p-value < 0.05 ดังนั้น ยอมรับ H1 นั่นคือ ร้านค้านี้ขายเมล็ดซึ่งมีเปอร์เซ็นต์การงอกสูงกว่าร้านค้าแรก < 5%

8.3 จากชุดข้อมูล "titanic.csv" จงทดสอบว่าส่วนเบี่ยงเบนมาตราฐานข้อมูลอายุผู้โดยสารมีค่าน้อยกว่า 10 ปีหรือไม่ที่ระดับความเชื่อมั่น 99% หากกำหนดให้ข้อมูลอายุผู้โดยสารมีการแจกแจงแบบปกติ

In [10]:
df = pd.read_csv("/content/drive/MyDrive/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [27]:
#แสดงสมมติฐาน พร้อมวิธีหาค่าcal ค่าp-value และการสรุปผล 

# Calculate the sample mean and standard deviation of age
age_mean = np.mean(df['Age'].dropna())
age_std = np.std(df['Age'].dropna(), ddof=1)
n = len(df['Age'].dropna())

pop_mean = 10

sample_std_err = age_std / np.sqrt(n)

t_stat = (age_mean - pop_mean) / sample_std_err

dof = n - 1
p_val = 2 * stats.t.cdf(-np.abs(t_stat), dof)

conf_int = stats.t.interval(alpha=0.99, df=dof, loc=age_mean, scale=age_std/np.sqrt(n))

print(f"{p_val:.5f}")
print("p_val < 0.01 ดังนั้นปฎิเสธ H0 นั่นคือ ข้อมูลอายุผู้โดยสารมีค่าน้อยกว่า 10")

0.00000
p_val < 0.01 ดังนั้นปฎิเสธ H0 นั่นคือ ข้อมูลอายุผู้โดยสารมีค่าน้อยกว่า 10

8.4 จากข้อ 8.3 จงทดสอบว่ากลุ่มผู้โดยสารชั้น Pclass = 1 มีความแปรปรวนของอายุเท่ากับ กลุ่มผู้โดยสารชั้น Pclass = 2 หรือไม่ที่ระดับนัยสำคัญ 0.05

In [21]:
#แสดงสมมติฐาน พร้อมวิธีหาค่าcal ค่าp-value และการสรุปผล 
age_pclass1 = df[df['Pclass']==1]['Age'].dropna()
age_pclass2 = df[df['Pclass']==2]['Age'].dropna()

var1 = np.var(age_pclass1, ddof=1)
var2 = np.var(age_pclass2, ddof=1)
f_stat = var1 / var2

alpha = 0.05
dof1 = len(age_pclass1) - 1
dof2 = len(age_pclass2) - 1
f_crit = ((1/alpha) - 1) * (dof2 / dof1)

if f_stat < f_crit or f_stat > 1/f_crit:
    print("ปฎิเสธ H0")
else:
    print("ยอมรับ H0")
print("ดังนั้น Pclass = 1 มีความแปรปรวนของอายุ(ไม่เท่ากับ) กลุ่มผู้โดยสารชั้น Pclass = 2")

ปฎิเสธ H0
ดังนั้น Pclass = 1 มีความแปรปรวนของอายุ(ไม่เท่ากับ) กลุ่มผู้โดยสารชั้น Pclass = 2